config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  resources :products
  resources :carts
  patch 'carts/:id/edit', controller: 'carts', action: :edit
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cartItems, class_name: "CartItem",
                      foreign_key: "cart_id",
                      dependent: :destroy
  has_many :products, through: :cartItems, source: :product
  accepts_nested_attributes_for :products, allow_destroy: true
  accepts_nested_attributes_for :cartItems, allow_destroy: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart, class_name: "Cart"
	belongs_to :product, class_name: "Product" 
	validates :cart_id,presence: true, :allow_nil => false
	validates :product_id,presence: true, :alow_nil => false
	validates :quantity, presence: true, :allow_nil => false
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cartItems
  validates :name, presence: true, :allow_nil => false
  validates :description, presence: true, :allow_nil => false
  validates :price, presence: true, :allow_nil => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ApplicationHelper	

  def edit
    session[:cart_id] = Cart.last.id
    cart_id = session[:cart_id]
    product_id = params[:product_id]
    quantity = params[:quantity]
    @cart = Cart.find_by(id: cart_id)
    if @cart.cartItems.count == 0 && !product_id
      byebug
      redirect_to root_path
    else
      if product_id

        if (cart_id && Cart.find(cart_id))
          if Cart.find(cart_id).cartItems.find_by(product_id: product_id)
            Cart.find(cart_id).cartItems.find_by(product_id:product_id).update_attribute(:quantity, quantity)
          else
            Cart.find(cart_id).cartItems.build(product_id: product_id, quantity:quantity).save
          end
        else
          @cart=Cart.new()
          @cart.save
          session[:cart_id] = Cart.last.id
          @cart.cartItems.build(product_id: product_id, quantity:quantity).save
        end
        respond_to do |f|
          f.html {return redirect_to root_path}
          f.js {return render json: {status: 'success', message: "Cart was updated"}}
        end
      else
        @cart = Cart.find(session[:cart_id])
      end  
    end
    
  end

  def destroy
    session[:cart_id] = nil
    @cart=Cart.new()
    @cart.save
    session[:cart_id] = @cart.id
    redirect_to root_path
  end

  def update
    @cart = Cart.find_by(id: session[:cart_id])
    @cart.update_attributes(cart_params)
    redirect_to edit_cart_path
  end


  private
    def create
      cart=Cart.new()
      session[:cart_id] = cart.id
    end

    def cart_params
      params.require(:cart).permit(cartItems_attributes:[:quantity, :id, :_destroy])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	session[:cart_id]=Cart.last.id
  	@products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_cart
  @current_cart= Cart.last
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/carts/edit.html.erb
<title>CartShopping</title>
<%=render 'layouts/header' %>  

<div class='container'>
  <h1>Cart #<%=session[:cart_id]%></h1>
  <%= form_for @cart do |f| %>
    <div class='row'>
      <%= f.fields_for :cartItems do |cartItem| %>
        <div class='col-md-3'>
          <div class='box'>
            <div class='box-header'>
              <%=cartItem.object.product.name%>
            </div>
            <div class='box-body'>   
              <%=cartItem.object.product.description%>
              <div class='price'>
                <p>
                  <b>Price:</b>
                  $<%=cartItem.object.product.price%>
                </p>
              </div>
            </div>
            <div class='box-footter'>
              <div class='row'>
                <div class='col-xs-6'>
                  <%=cartItem.number_field:quantity, :value => cartItem.object.quantity %>
                </div>
              </div>
              Remove: <%= cartItem.check_box :_destroy%>
            </div>
          </div>
        </div> 
      <%end%>
    </div>
    <div class='footer'>
      <%=link_to "Delete",cart_path(@cart.id) ,method: :delete %>
      <%=f.submit 'Save changes', class:"btn btn-primary"  %>
    </div>
  <%end%> 
</div>

app/views/carts/show.html.erb
<title>CartShopping</title>
<%=render 'layouts/header' %>  
<%= form_for(@cart) do |c|%>
  <% @cart.products.each do |p|%>
    <%=form_for(p) do |d|%>
      <%= p.name %>
      <input value=<%=@cart.cartItems.find_by(product_id: p.id).quantity%> min="1" class="form-control" type="number" name="quantity" id="item_quantity">
    <%end%>
  <%end%>
  <%= c.submit "Create my account", class: "btn btn-primary" %>
<%end%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
   <div class="container">
      <div class="navbar-header">
         <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#cart_shopping_collapse" data-toggle="collapse" type="button">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand">
         Cart shopping
         </a>
      </div>
      <div class="collapse navbar-collapse" id="cart_shopping_collapse">
         <ul class="nav navbar-nav">
            <li>
               <%= link_to "Home", root_path%>
            </li>
            <li>
               <%= link_to "Product", root_path %>
            </li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
            <li>
               <%= link_to "Cart", edit_cart_path(session[:cart_id]) %>
            </li>
         </ul>
      </div>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
   <head>
   </head>
   <body>
      <%=render 'layouts/header' %>
      <div class="container">
      <h1>All products</h1>
      <h4></h4>
      <div class="row">
         <% @products.each do |p| %> 
         <%=form_for(p, url: edit_cart_path(p), remote: true) do |f|%> 
         <%=hidden_field_tag( :product_id,p.id)%> 
            <div class="col-md-3">
               <div class="box">
                  <div class="box-header">
                     <%=p.name%>
                  </div>
                  <div class="box-body">
                     <p><%=p.description%></p>
                     <div class="price">
                        <p>
                           <b>Price:</b>
                           $<%=p.price%>
                        </p>
                     </div>
                  </div>


                  <div class="box-footter">
                     <form class="new_item" id="new_item" action=edit_cart_path(p) accept-charset="UTF-8" data-remote="true" method="post">
                        <input name="utf8" type="hidden" value="✓">
                        <div class="row">
                           
                           <div class="col-xs-6">
                              <input value="1" type="hidden" name="quantity[product_id]" id="item_product_id">
                              <input value="1" min="1" class="form-control" type="number" name="quantity" id="item_quantity">
                           </div>
                            
                           <%= submit_tag("Add to cart", class:"btn btn-success")%>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
            
         <%end%>
            
         <% end %>
         </div>
      </div>
   </body>
</html>